name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS via SSH
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          TARGET_DIR: /home/${{ secrets.VPS_USER }}/ffabrika-client
          APP_NAME: ffabrika-client
          PORT: 3000
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            cd $TARGET_DIR
            git fetch --all --prune
            git reset --hard origin/main
            pnpm install --prod --frozen-lockfile
            pnpm run build
            if pm2 list | grep -q $APP_NAME; then
              pm2 reload $APP_NAME
            else
              pm2 start .output/server/index.mjs --name $APP_NAME -- --port=$PORT
            fi
            pm2 save
          EOF
