name: Auto Deploy FFabrika Client

on:
  push:
    branches: [main]

jobs:
  deploy-client:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Pull latest FFabrika Client
        run: |
          cd /home/fastuser/ffabrika-client
          git pull origin main

      - name: Fix ownership before install
        run: |
          sudo chown -R fastuser:fastuser /home/fastuser/ffabrika-client

      - name: Install dependencies
        run: |
          cd /home/fastuser/ffabrika-client
          chmod +x node_modules/.pnpm/@esbuild+linux-x64@*/node_modules/@esbuild/linux-x64/bin/esbuild
          pnpm install --reporter=append-only --loglevel=debug

      - name: Build project
        run: |
          cd /home/fastuser/ffabrika-client
          pnpm run build

      - name: Reload with PM2
        run: |
          cd /home/fastuser/ffabrika-client
          pm2 reload ffabrika-client \
            || pm2 start npx --name ffabrika-client -- nuxi dev . --host 0.0.0.0 --port 3000
