name: Auto Deploy FFabrika Client

on:
  push:
    branches: [main]

jobs:
  deploy-client:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Pull latest FFabrika Client
        run: |
          cd /home/fastuser/ffabrika-client
          git pull origin main
