name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ffabrika]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to VPS via SSH
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: fastuser
          VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
          TARGET_DIR: /home/fastuser/ffabrika-client
          APP_NAME: ffabrika-client
        run: |
          set -e
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            cd $TARGET_DIR
            git fetch --all --prune
            git reset --hard origin/main
            pnpm install
            pnpm run build
            pm2 reload $APP_NAME || pm2 start npx --name $APP_NAME -- nuxi dev . --host 0.0.0.0 --port 3000
            pm2 save
          EOF
