name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ffabrika]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to VPS via SSH
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USER }}
          TARGET_DIR: ${{ secrets.VPS_TARGET_DIR }}
          APP_NAME: ffabrika-client
        run: |
          set -e
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            cd $TARGET_DIR
            git fetch --all --prune
            git reset --hard origin/main
            pnpm install
            pnpm run build
            pm2 reload $APP_NAME || pm2 start npx --name $APP_NAME -- nuxi dev . --host 0.0.0.0 --port 3000
            pm2 save
          EOF
