name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, ffabrika]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: fastuser
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /home/fastuser/ffabrika-client
            git fetch --all --prune
            git reset --hard origin/main
            pnpm install
            pnpm run build
            pm2 reload ffabrika-client || pm2 start npx --name ffabrika-client -- nuxi dev . --host 0.0.0.0 --port 3000
            pm2 save
