name: Deploy to VPS via SSH

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: [self-hosted, ffabrika]
    steps:
      - name: Pull latest code on server
        run: |
          cd /home/fastuser/ffabrika-client
          git pull origin main
