name: Deploy to VPS via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted, ffabrika]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add VPS to known_hosts
        run: ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=yes \
              -o UserKnownHostsFile=~/.ssh/known_hosts \
              -tt fastuser@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/fastuser/ffabrika-client
            git fetch --all --prune
            git reset --hard origin/main
            pnpm install
            pnpm run build
            pm2 reload ffabrika-client || pm2 start npx --name ffabrika-client -- nuxi dev . --host 0.0.0.0 --port 3000
            pm2 save
          EOF
